package hibernate.orm;
// Generated 2013-9-5 10:00:19 by Hibernate Tools 3.2.1.GA



/**
 * HatCity generated by hbm2java
 */
public class HatCity  implements java.io.Serializable {


     private int id;
     private String cityId;
     private String city;
     private String father;

    public HatCity() {
    }

	
    public HatCity(int id) {
        this.id = id;
    }
    public HatCity(int id, String cityId, String city, String father) {
       this.id = id;
       this.cityId = cityId;
       this.city = city;
       this.father = father;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCityId() {
        return this.cityId;
    }
    
    public void setCityId(String cityId) {
        this.cityId = cityId;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getFather() {
        return this.father;
    }
    
    public void setFather(String father) {
        this.father = father;
    }




}


