package hibernate.orm;
// Generated 2013-9-5 10:00:19 by Hibernate Tools 3.2.1.GA



/**
 * HatProvince generated by hbm2java
 */
public class HatProvince  implements java.io.Serializable {


     private int id;
     private String provinceId;
     private String province;

    public HatProvince() {
    }

	
    public HatProvince(int id) {
        this.id = id;
    }
    public HatProvince(int id, String provinceId, String province) {
       this.id = id;
       this.provinceId = provinceId;
       this.province = province;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getProvinceId() {
        return this.provinceId;
    }
    
    public void setProvinceId(String provinceId) {
        this.provinceId = provinceId;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }




}


