package hibernate.orm;
// Generated 2013-9-5 10:00:19 by Hibernate Tools 3.2.1.GA



/**
 * Street generated by hbm2java
 */
public class Street  implements java.io.Serializable {


     private int idstreet;
     private String streetcol;

    public Street() {
    }

	
    public Street(int idstreet) {
        this.idstreet = idstreet;
    }
    public Street(int idstreet, String streetcol) {
       this.idstreet = idstreet;
       this.streetcol = streetcol;
    }
   
    public int getIdstreet() {
        return this.idstreet;
    }
    
    public void setIdstreet(int idstreet) {
        this.idstreet = idstreet;
    }
    public String getStreetcol() {
        return this.streetcol;
    }
    
    public void setStreetcol(String streetcol) {
        this.streetcol = streetcol;
    }




}


