package hibernate.orm;
// Generated 2013-9-5 10:00:19 by Hibernate Tools 3.2.1.GA



/**
 * Subject generated by hbm2java
 */
public class Subject  implements java.io.Serializable {


     private int id;
     private User user;
     private String subject;
     private String price;

    public Subject() {
    }

	
    public Subject(int id, User user) {
        this.id = id;
        this.user = user;
    }
    public Subject(int id, User user, String subject, String price) {
       this.id = id;
       this.user = user;
       this.subject = subject;
       this.price = price;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }




}


