package hibernate.orm;
// Generated 2013-9-5 10:00:19 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TutorInfo generated by hbm2java
 */
public class TutorInfo  implements java.io.Serializable {


     private int id;
     private User user;
     private String phone;
     private String eduDegree;
     private String sex;
     private String age;
     private String way;
     private String techTime;
     private Date loginTime;
     private String identy;

    public TutorInfo() {
    }

	
    public TutorInfo(int id, User user, String phone, String eduDegree, Date loginTime, String identy) {
        this.id = id;
        this.user = user;
        this.phone = phone;
        this.eduDegree = eduDegree;
        this.loginTime = loginTime;
        this.identy = identy;
    }
    public TutorInfo(int id, User user, String phone, String eduDegree, String sex, String age, String way, String techTime, Date loginTime, String identy) {
       this.id = id;
       this.user = user;
       this.phone = phone;
       this.eduDegree = eduDegree;
       this.sex = sex;
       this.age = age;
       this.way = way;
       this.techTime = techTime;
       this.loginTime = loginTime;
       this.identy = identy;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEduDegree() {
        return this.eduDegree;
    }
    
    public void setEduDegree(String eduDegree) {
        this.eduDegree = eduDegree;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public String getAge() {
        return this.age;
    }
    
    public void setAge(String age) {
        this.age = age;
    }
    public String getWay() {
        return this.way;
    }
    
    public void setWay(String way) {
        this.way = way;
    }
    public String getTechTime() {
        return this.techTime;
    }
    
    public void setTechTime(String techTime) {
        this.techTime = techTime;
    }
    public Date getLoginTime() {
        return this.loginTime;
    }
    
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }
    public String getIdenty() {
        return this.identy;
    }
    
    public void setIdenty(String identy) {
        this.identy = identy;
    }




}


