package hibernate.orm;
// Generated 2013-9-5 10:00:19 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String userid;
     private String username;
     private String password;
     private String email;
     private Date registeTime;
     private String mobile;
     private Set tutorInfos = new HashSet(0);
     private Set photos = new HashSet(0);
     private Set addresses = new HashSet(0);
     private Set wealths = new HashSet(0);
     private Set subjects = new HashSet(0);

    public User() {
    }

	
    public User(String userid, String username, String password, String email, Date registeTime) {
        this.userid = userid;
        this.username = username;
        this.password = password;
        this.email = email;
        this.registeTime = registeTime;
    }
    public User(String userid, String username, String password, String email, Date registeTime, String mobile, Set tutorInfos, Set photos, Set addresses, Set wealths, Set subjects) {
       this.userid = userid;
       this.username = username;
       this.password = password;
       this.email = email;
       this.registeTime = registeTime;
       this.mobile = mobile;
       this.tutorInfos = tutorInfos;
       this.photos = photos;
       this.addresses = addresses;
       this.wealths = wealths;
       this.subjects = subjects;
    }
   
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getRegisteTime() {
        return this.registeTime;
    }
    
    public void setRegisteTime(Date registeTime) {
        this.registeTime = registeTime;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public Set getTutorInfos() {
        return this.tutorInfos;
    }
    
    public void setTutorInfos(Set tutorInfos) {
        this.tutorInfos = tutorInfos;
    }
    public Set getPhotos() {
        return this.photos;
    }
    
    public void setPhotos(Set photos) {
        this.photos = photos;
    }
    public Set getAddresses() {
        return this.addresses;
    }
    
    public void setAddresses(Set addresses) {
        this.addresses = addresses;
    }
    public Set getWealths() {
        return this.wealths;
    }
    
    public void setWealths(Set wealths) {
        this.wealths = wealths;
    }
    public Set getSubjects() {
        return this.subjects;
    }
    
    public void setSubjects(Set subjects) {
        this.subjects = subjects;
    }




}


